###########
# site.title

title:    'Daniel's Minimum Viable CV'
subtitle: 'Maximally Viable Candidate'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
